export const slides = [
  {
    title: 'Планкіт Грейджой',
    itemNumber: 10001,
    collection: 'Plankit',
    design: 'Greyjoy',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ' +
    'labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut' +
    ' aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ' +
    'dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia ' +
    'deserunt mollit anim id est laborum.',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgSmall: './assets/plankit/imgsmall/sm_greyjoy.jpg',
    srcImgBig: './assets/plankit/imgbig/greyjoy.jpg',
    srcImgBig2: './assets/plankit/imgbig/h_greyjoy.png',
  },
  {
    title: 'Планкіт Ерін',
    itemNumber: 10002,
    collection: 'Plankit',
    design: 'Arryn',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgSmall: './assets/plankit/imgsmall/sm_arryn.jpg',
    srcImgBig: './assets/plankit/imgbig/arryn.jpg',
    srcImgBig2: './assets/plankit/imgbig/h_arryn.png',
  },
  {
    title: 'Планкіт Баратеон',
    itemNumber: 10003,
    collection: 'Plankit',
    design: 'Baratheon',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgSmall: './assets/plankit/imgsmall/sm_baratheon.jpg',
    srcImgBig: './assets/plankit/imgbig/baratheon.jpg',
    srcImgBig2: './assets/plankit/imgbig/h_baratheon.png',
  },
  {
    title: 'Планкіт Мормонт',
    itemNumber: 10004,
    collection: 'Plankit',
    design: 'Mormont',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgSmall: './assets/plankit/imgsmall/sm_mormont.jpg',
    srcImgBig: './assets/plankit/imgbig/mormont.jpg',
    srcImgBig2: './assets/plankit/imgbig/h_mormont.png',
  },
  {
    title: 'Планкіт Старк',
    itemNumber: 10005,
    collection: 'Plankit',
    design: 'Stark',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgSmall: './assets/plankit/imgsmall/sm_stark.jpg',
    srcImgBig: './assets/plankit/imgbig/stark.jpg',
    srcImgBig2: './assets/plankit/imgbig/h_stark.png',
  },
];
