export const slides = [
  {
    title: 'Планкіт Грейджой',
    itemNumber: 10001,
    collection: 'Plankit',
    design: 'Greyjoy',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut ' +
    'labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut' +
    ' aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum ' +
    'dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia ' +
    'deserunt mollit anim id est laborum.',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgMain: './assets/plankit/img_main/w_greyjoy.jpg',
    srcImgSmall: './assets/plankit/img_small/wood_square/sm_w_s_greyjoy.jpg',
    srcImgSmall2: './assets/plankit/img_small/wood_vertical/sm_w_v_greyjoy.jpg',
    srcImgBig: './assets/plankit/img_big/wood_square/big_w_s_greyjoy.jpg',
    srcImgBig2: './assets/plankit/img_big/wood_vertical/big_w_v_greyjoy.jpg',
  },
  {
    title: 'Планкіт Ерін',
    itemNumber: 10002,
    collection: 'Plankit',
    design: 'Arryn',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgMain: './assets/plankit/img_main/w_arryn.jpg',
    srcImgSmall: './assets/plankit/img_small/wood_square/sm_w_s_arryn.jpg',
    srcImgSmall2: './assets/plankit/img_small/wood_vertical/sm_w_v_arryn.jpg',
    srcImgBig: './assets/plankit/img_big/wood_square/big_w_s_arryn.jpg',
    srcImgBig2: './assets/plankit/img_big/wood_vertical/big_w_v_arryn.jpg',
  },
  {
    title: 'Планкіт Баратеон',
    itemNumber: 10003,
    collection: 'Plankit',
    design: 'Baratheon',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgMain: './assets/plankit/img_main/w_baratheon.jpg',
    srcImgSmall: './assets/plankit/img_small/wood_square/sm_w_s_baratheon.jpg',
    srcImgSmall2: './assets/plankit/img_small/wood_vertical/sm_w_v_baratheon.jpg',
    srcImgBig: './assets/plankit/img_big/wood_square/big_w_s_baratheon.jpg',
    srcImgBig2: './assets/plankit/img_big/wood_vertical/big_w_v_baratheon.jpg',
  },
  {
    title: 'Планкіт Мормонт',
    itemNumber: 10004,
    collection: 'Plankit',
    design: 'Mormont',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgMain: './assets/plankit/img_main/w_mormont.jpg',
    srcImgSmall: './assets/plankit/img_small/wood_square/sm_w_s_mormont.jpg',
    srcImgSmall2: './assets/plankit/img_small/wood_vertical/sm_w_v_mormont.jpg',
    srcImgBig: './assets/plankit/img_big/wood_square/big_w_s_mormont.jpg',
    srcImgBig2: './assets/plankit/img_big/wood_vertical/big_w_v_mormont.jpg',
  },
  {
    title: 'Планкіт Старк',
    itemNumber: 10005,
    collection: 'Plankit',
    design: 'Stark',
    description: '',
    regularPrice: 300,
    sale: false,
    salePrice: 285,
    show: true,
    active: true,
    srcImgMain: './assets/plankit/img_main/w_stark.jpg',
    srcImgSmall: './assets/plankit/img_small/wood_square/sm_w_s_stark.jpg',
    srcImgSmall2: './assets/plankit/img_small/wood_vertical/sm_w_v_stark.jpg',
    srcImgBig: './assets/plankit/img_big/wood_square/big_w_s_stark.jpg',
    srcImgBig2: './assets/plankit/img_big/wood_vertical/big_w_v_stark.jpg',
  },
];
